version: '3.8'

services:
  postgres:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_consultancy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/ai_consultancy
      - REDIS_URL=redis://redis:6379
      - RENDER_JWT_SECRET=${JWT_SECRET:-local-development-secret}
      - RENDER_OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile.backend.worker
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/ai_consultancy
      - REDIS_URL=redis://redis:6379
      - RENDER_JWT_SECRET=${JWT_SECRET:-local-development-secret}
      - RENDER_OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - NEXTAUTH_SECRET=local-development-secret
      - NEXTAUTH_URL=http://localhost:3001
    ports:
      - "3001:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
