services:
  # Frontend Web Service
  - type: web
    name: ai-consultancy
    env: node
    region: oregon
    plan: free
    branch: main
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://ai-consultancy-backend.onrender.com
      - key: NEXTAUTH_URL
        value: https://ai-consultancy.onrender.com
      - key: NEXTAUTH_SECRET
        sync: false # Will be set manually in Render dashboard
    autoDeploy: true
