services:
  - type: web
    name: bengalmindai-consultancy
    env: static
    buildCommand: ./build.sh
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NPM_CONFIG_PRODUCTION
        value: false